from typing import Protocol

from email_agent.models import Draft, EmailMessage, EmailThread


class MailProvider(Protocol):
    """Mailbox operations required by the provider-independent pipeline."""

    def get_messages(self, limit: int = 20, *, unread_only: bool = False) -> list[EmailMessage]: ...
    def get_new_messages(self, limit: int = 20) -> list[EmailMessage]: ...
    def get_message(self, message_id: str) -> EmailMessage: ...
    def get_thread(self, message_id: str) -> EmailThread: ...
    def create_draft(self, message_id: str, body: str) -> Draft: ...
    def mark_processed(self, message_id: str) -> None: ...
    def sync_category(self, message_id: str, destination: str) -> None: ...
